name       : numactl
version    : 2.0.13
release    : 1
source     :
    - https://github.com/numactl/numactl/archive/v2.0.13.tar.gz : 97ee012b2f294903530424b4ff7f28bcaad6a356897ce8777383f87e5c2e325d
license    : GPL-2.0
             GLPL-2.1
component  : programming.devel
summary    : Simple NUMA policy support. It consists of a numactl program to run other programs with a specific NUMA policy and a libnuma shared library ("NUMA API") to set NUMA policy in applications.
description: |
    Simple NUMA policy support. It consists of a numactl program to run other programs with a specific NUMA policy and a libnuma shared library ("NUMA API") to set NUMA policy in applications.
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
    find $installdir -name "*.a" -type f -delete
