name       : roct-thunk-interface
version    : 3.1.0
release    : 1
source     : 
    - https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/roc-3.1.0.tar.gz : b08176b5f4af39d0160990f9f1dea5d27974f9282f544140b4a41d19446fe570
license    : MIT
component  : programming.devel
summary    : This repository includes the user-mode API interfaces used to interact with the ROCk driver. Currently supported agents include only the AMD/ATI Fiji family of discrete GPUs.
description: |
    This repository includes the user-mode API interfaces used to interact with the ROCk driver. Currently supported agents include only the AMD/ATI Fiji family of discrete GPUs.
builddeps  :
    - pkgconfig(libpci)
    - pkgconfig(numa)
setup      : |
    mkdir -p build/
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$installdir/usr ..
build      : |
    cd build
    %make
install    : |
   cd build
   %cmake- -DCMAKE_INSTALL_PREFIX=$installdir/usr -P cmake_install.cmake

   
   cd ../include
   install -Dm00644 hsakmt.h $installdir/usr/include/hsakmt.h
   install -Dm00644 hsakmttypes.h $installdir/usr/include/hsakmttypes.h
    
